# 1. Configurações de Upload (máximo de 10MB por arquivo, ajustável conforme necessário)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# 2. Conexão com o Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/casamento_db
spring.datasource.username=postgres
spring.datasource.password=10091971Isa.

# 3. Configurações do JPA e Hibernate (A Mágica)
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true